/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package reproductor;

import java.awt.Color;
import java.awt.Dimension;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.StandardCopyOption;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JProgressBar;
import javax.swing.Timer;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.plaf.basic.BasicProgressBarUI;

/**
 *
 * @author elean
 */
public class Reproductor extends javax.swing.JFrame {

    private MusicPlayer player;
    private Timer timer;
    private JList<String> playlist, playlist2;
    private DefaultListModel<String> listModel;

    public Reproductor() {
        initComponents();

        Fondo1.setVisible(true);
        Reproductor.setVisible(true);
        Label.setVisible(true);
        jLabel1.setVisible(false);
        jLabel2.setVisible(false);
        jLabel3.setVisible(false);
        jLabel4.setVisible(false);
        jLabel5.setVisible(false);
        jLabel6.setVisible(false);
        jLabel7.setVisible(false);
        jLabel8.setVisible(false);

        Fondo.setVisible(false);
        BotonAgregarCancion.setVisible(false);
        Regresar.setVisible(false);
        BotonPlay.setVisible(false);
        JProgressBar.setVisible(false);
        DuracionLabel.setVisible(false);
        BotonStop.setVisible(false);
        CurrentLabel.setVisible(false);
        CancionNombreLabel.setVisible(false);
        BotonPause.setVisible(false);

        player = new MusicPlayer();
        listModel = new DefaultListModel<>();
        playlist = new JList<>(listModel);
        jScrollPane1.setViewportView(playlist);

        timer = new Timer(100, e -> {
            if (player.isPlaying()) {
                long currentSeconds = player.getCurrentMicroseconds() / 1_000_000;
                long totalSeconds = player.getTotalSeconds();
                int progress = (int) ((double) currentSeconds / totalSeconds * 100);
                JProgressBar.setValue(progress);

                long minutes = totalSeconds / 60;
                long seconds = totalSeconds % 60;
                DuracionLabel.setText(String.format("%02d:%02d", minutes, seconds));

                long currentMinutes = currentSeconds / 60;
                long currentSecondsRemaining = currentSeconds % 60;
                CurrentLabel.setText(String.format("%02d:%02d", currentMinutes, currentSecondsRemaining));
            }
        });

        playlist.addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) {
                int index = playlist.getSelectedIndex();
                if (index != -1) {
                    player.selectSong(index);
                    CancionNombreLabel.setText(listModel.getElementAt(index));
                    JProgressBar.setValue(0);
                }
            }
        });

        loadSongsFromDefaultFolder();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Reproducir = new javax.swing.JPanel();
        BotonAgregarCancion = new javax.swing.JLabel();
        Reproductor = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListaCanciones = new javax.swing.JList<>();
        Regresar = new javax.swing.JLabel();
        BotonPlay = new javax.swing.JLabel();
        JProgressBar = new javax.swing.JProgressBar();
        DuracionLabel = new javax.swing.JLabel();
        BotonStop = new javax.swing.JLabel();
        CurrentLabel = new javax.swing.JLabel();
        CancionNombreLabel = new javax.swing.JLabel();
        BotonPause = new javax.swing.JLabel();
        Label = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();
        Fondo1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Reproducir.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BotonAgregarCancion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonAgregarCancion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonAgregarCancionMouseClicked(evt);
            }
        });
        Reproducir.add(BotonAgregarCancion, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 470, 40, 40));

        Reproductor.setToolTipText("Ir al Reproductor");
        Reproductor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Reproductor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ReproductorMouseClicked(evt);
            }
        });
        Reproducir.add(Reproductor, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 250, 90, 90));

        jScrollPane1.setBorder(null);
        jScrollPane1.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N

        ListaCanciones.setBackground(new java.awt.Color(255, 255, 255));
        ListaCanciones.setFont(new java.awt.Font("Microsoft YaHei", 1, 18)); // NOI18N
        ListaCanciones.setForeground(new java.awt.Color(0, 0, 0));
        ListaCanciones.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ListaCanciones.setSelectionBackground(new java.awt.Color(255, 204, 255));
        ListaCanciones.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(ListaCanciones);

        Reproducir.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 160, 420, 310));

        Regresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegresarMouseClicked(evt);
            }
        });
        Reproducir.add(Regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 50, 40));

        BotonPlay.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonPlay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonPlayMouseClicked(evt);
            }
        });
        Reproducir.add(BotonPlay, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 360, 80, 90));

        JProgressBar.setBackground(new java.awt.Color(255, 255, 255));
        JProgressBar.setForeground(new java.awt.Color(255, 204, 204));
        Reproducir.add(JProgressBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 290, 400, 30));

        DuracionLabel.setFont(new java.awt.Font("Microsoft YaHei", 1, 18)); // NOI18N
        DuracionLabel.setForeground(new java.awt.Color(255, 255, 255));
        DuracionLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        DuracionLabel.setText("00:00");
        Reproducir.add(DuracionLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(417, 330, 60, 30));

        BotonStop.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonStop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonStopMouseClicked(evt);
            }
        });
        Reproducir.add(BotonStop, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 360, 90, 90));

        CurrentLabel.setFont(new java.awt.Font("Microsoft YaHei", 1, 18)); // NOI18N
        CurrentLabel.setForeground(new java.awt.Color(255, 255, 255));
        CurrentLabel.setText("00:00");
        Reproducir.add(CurrentLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, 60, 30));

        CancionNombreLabel.setFont(new java.awt.Font("Microsoft YaHei", 1, 20)); // NOI18N
        CancionNombreLabel.setForeground(new java.awt.Color(255, 255, 255));
        CancionNombreLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CancionNombreLabel.setText("No Song Selected");
        Reproducir.add(CancionNombreLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 239, 400, 40));

        BotonPause.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonPause.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonPauseMouseClicked(evt);
            }
        });
        Reproducir.add(BotonPause, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 360, 80, 90));

        Label.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                LabelKeyReleased(evt);
            }
        });
        Reproducir.add(Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 160, 160));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Sofia.png"))); // NOI18N
        jLabel8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jLabel8KeyReleased(evt);
            }
        });
        Reproducir.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 160, 160));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Sia.png"))); // NOI18N
        jLabel7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jLabel7KeyReleased(evt);
            }
        });
        Reproducir.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 160, 160));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Sabrina.png"))); // NOI18N
        jLabel6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jLabel6KeyReleased(evt);
            }
        });
        Reproducir.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 160, 160));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Neighbourhood.png"))); // NOI18N
        jLabel5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jLabel5KeyReleased(evt);
            }
        });
        Reproducir.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 160, 160));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Melanie.png"))); // NOI18N
        jLabel4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jLabel4KeyReleased(evt);
            }
        });
        Reproducir.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 160, 160));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Ember.png"))); // NOI18N
        jLabel3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jLabel3KeyReleased(evt);
            }
        });
        Reproducir.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 160, 160));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Dove.png"))); // NOI18N
        jLabel2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jLabel2KeyReleased(evt);
            }
        });
        Reproducir.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 160, 160));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Ariana.png"))); // NOI18N
        jLabel1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jLabel1KeyReleased(evt);
            }
        });
        Reproducir.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 160, 160));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reproductor/Reproducir Musica.png"))); // NOI18N
        Reproducir.add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Fondo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reproductor/Reproducir.png"))); // NOI18N
        Reproducir.add(Fondo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(Reproducir, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ReproductorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReproductorMouseClicked
        Fondo.setVisible(true);
        BotonAgregarCancion.setVisible(true);
        Regresar.setVisible(true);
        BotonPlay.setVisible(true);
        JProgressBar.setVisible(true);
        DuracionLabel.setVisible(true);
        BotonStop.setVisible(true);
        CurrentLabel.setVisible(true);
        CancionNombreLabel.setVisible(true);
        BotonPause.setVisible(true);
        jScrollPane1.setBounds(50, 110, 730, 360);

        Fondo1.setVisible(false);
        Reproductor.setVisible(false);
    }//GEN-LAST:event_ReproductorMouseClicked

    private void BotonPauseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonPauseMouseClicked
        if (player.isPlaying()) {
            player.pause();
        } else {
            player.resume();
        }
    }//GEN-LAST:event_BotonPauseMouseClicked

    private void BotonStopMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonStopMouseClicked
        player.stop();
        JProgressBar.setValue(0);
        if (timer.isRunning()) {
            timer.stop();
        }
    }//GEN-LAST:event_BotonStopMouseClicked

    private void BotonPlayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonPlayMouseClicked
        int selectedIndex = playlist.getSelectedIndex();
        if (selectedIndex != -1) {
            player.selectSong(selectedIndex);
            player.play();
            updateProgressBar();

            if (selectedIndex == 0 || selectedIndex == 1) {
                jLabel1.setVisible(true);
                jLabel2.setVisible(false);
                jLabel3.setVisible(false);
                jLabel4.setVisible(false);
                jLabel5.setVisible(false);
                jLabel6.setVisible(false);
                jLabel7.setVisible(false);
                jLabel8.setVisible(false);
            } else if (selectedIndex == 2) {
                jLabel2.setVisible(true);
                jLabel1.setVisible(false);
                jLabel3.setVisible(false);
                jLabel4.setVisible(false);
                jLabel5.setVisible(false);
                jLabel6.setVisible(false);
                jLabel7.setVisible(false);
                jLabel8.setVisible(false);
            } else if (selectedIndex == 3) {
                jLabel2.setVisible(false);
                jLabel1.setVisible(false);
                jLabel3.setVisible(true);
                jLabel4.setVisible(false);
                jLabel5.setVisible(false);
                jLabel6.setVisible(false);
                jLabel7.setVisible(false);
                jLabel8.setVisible(false);
            } else if (selectedIndex == 4) {
                jLabel2.setVisible(false);
                jLabel1.setVisible(false);
                jLabel3.setVisible(false);
                jLabel4.setVisible(true);
                jLabel5.setVisible(false);
                jLabel6.setVisible(false);
                jLabel7.setVisible(false);
                jLabel8.setVisible(false);
            } else if (selectedIndex == 5 || selectedIndex == 6) {
                jLabel2.setVisible(false);
                jLabel1.setVisible(false);
                jLabel3.setVisible(false);
                jLabel4.setVisible(false);
                jLabel5.setVisible(false);
                jLabel6.setVisible(true);
                jLabel7.setVisible(false);
                jLabel8.setVisible(false);
            } else if (selectedIndex == 7) {
                jLabel2.setVisible(false);
                jLabel1.setVisible(false);
                jLabel3.setVisible(false);
                jLabel4.setVisible(false);
                jLabel5.setVisible(false);
                jLabel6.setVisible(false);
                jLabel7.setVisible(true);
                jLabel8.setVisible(false);
            } else if (selectedIndex == 8) {
                jLabel2.setVisible(false);
                jLabel1.setVisible(false);
                jLabel3.setVisible(false);
                jLabel4.setVisible(false);
                jLabel5.setVisible(false);
                jLabel6.setVisible(false);
                jLabel7.setVisible(false);
                jLabel8.setVisible(true);
            } else if (selectedIndex == 9) {
                jLabel2.setVisible(false);
                jLabel1.setVisible(false);
                jLabel3.setVisible(false);
                jLabel4.setVisible(false);
                jLabel5.setVisible(true);
                jLabel6.setVisible(false);
                jLabel7.setVisible(false);
                jLabel8.setVisible(false);
            }

        } else {
            JOptionPane.showMessageDialog(this, "No hay canción seleccionada.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BotonPlayMouseClicked

    private void RegresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegresarMouseClicked
        Fondo1.setVisible(true);

        jScrollPane1.setBounds(500, 160, 420, 310);

        Reproductor.setVisible(true);

        Fondo.setVisible(false);
        BotonAgregarCancion.setVisible(false);
        Regresar.setVisible(false);
        BotonPlay.setVisible(false);
        JProgressBar.setVisible(false);
        DuracionLabel.setVisible(false);
        BotonStop.setVisible(false);
        CurrentLabel.setVisible(false);
        CancionNombreLabel.setVisible(false);
        BotonPause.setVisible(false);

        jLabel1.setVisible(false);
        jLabel2.setVisible(false);
        jLabel3.setVisible(false);
        jLabel4.setVisible(false);
        jLabel5.setVisible(false);
        jLabel6.setVisible(false);
        jLabel7.setVisible(false);
        jLabel8.setVisible(false);
    }//GEN-LAST:event_RegresarMouseClicked

    private void BotonAgregarCancionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonAgregarCancionMouseClicked
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        fileChooser.setFileFilter(new FileNameExtensionFilter("WAV files", "wav"));
        int returnValue = fileChooser.showOpenDialog(null);
        if (returnValue == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            File musicFolder = new File("src/Music");
            if (!musicFolder.exists()) {
                musicFolder.mkdirs();
            }
            File newFile = new File(musicFolder, selectedFile.getName());
            try {
                Files.copy(selectedFile.toPath(), newFile.toPath(), StandardCopyOption.REPLACE_EXISTING);
                listModel.addElement(selectedFile.getName().replace(".wav", ""));
                player.addSong(newFile.getAbsolutePath());
            } catch (IOException ex) {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_BotonAgregarCancionMouseClicked

    private void jLabel1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel1KeyReleased

    }//GEN-LAST:event_jLabel1KeyReleased

    private void jLabel2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel2KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2KeyReleased

    private void LabelKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LabelKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_LabelKeyReleased

    private void jLabel3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel3KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel3KeyReleased

    private void jLabel4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel4KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel4KeyReleased

    private void jLabel5KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel5KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel5KeyReleased

    private void jLabel6KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel6KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel6KeyReleased

    private void jLabel7KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel7KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel7KeyReleased

    private void jLabel8KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel8KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel8KeyReleased

    private void loadSongsFromDefaultFolder() {
        File musicFolder = new File("src/Music");
        if (musicFolder.exists() && musicFolder.isDirectory()) {
            File[] files = musicFolder.listFiles((dir, name) -> name.toLowerCase().endsWith(".wav"));
            if (files != null) {
                for (File file : files) {
                    listModel.addElement(file.getName().replace(".wav", ""));
                    player.addSong(file.getAbsolutePath());
                }
            }
        }
    }

    private void updateProgressBar() {
        if (!timer.isRunning()) {
            timer.start();
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reproductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reproductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reproductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reproductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reproductor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BotonAgregarCancion;
    private javax.swing.JLabel BotonPause;
    private javax.swing.JLabel BotonPlay;
    private javax.swing.JLabel BotonStop;
    private javax.swing.JLabel CancionNombreLabel;
    private javax.swing.JLabel CurrentLabel;
    private javax.swing.JLabel DuracionLabel;
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel Fondo1;
    private javax.swing.JProgressBar JProgressBar;
    private javax.swing.JLabel Label;
    private javax.swing.JList<String> ListaCanciones;
    private javax.swing.JLabel Regresar;
    private javax.swing.JPanel Reproducir;
    private javax.swing.JLabel Reproductor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
